version: 2.1

executors:
  nodeandroiddocker:
    docker:
      - image: circleci/android:api-29-node
    resource_class: large
    working_directory: ~/NativescriptAppBuild

fast-checkout: &fast-checkout
  attach_workspace:
    at: ~/

jobs:
  CheckoutCode:
    executor: nodeandroiddocker
    steps:
        - checkout
#       - run: rm -rf .git
        - persist_to_workspace:
            root: ~/
            paths:
                - NativescriptAppBuild

  setupGlobal:
    executor: nodeandroiddocker
    steps:
      - restore_cache:
          keys:
            - v3-npm-global

      - run:
          name: Install npm modules
          command: |
            npm config set prefix '~/npm-global'
            npm i -g standard prettier --ignore-scripts --unsafe-perm --no-progress;
            npm i -g nativescript-app-sync-cli nativescript firebase-tools --ignore-scripts --unsafe-perm --no-progress;

      - save_cache:
          paths:
            - ~/npm-global
          key: v3-npm-global


  styleCheck:
    executor: nodeandroiddocker
    steps:
      - *fast-checkout

      - restore_cache:
          keys:
            - v3-npm-global

      - run:
          name: Prettier on app js files
          command: |
            ~/npm-global/bin/prettier --write "app/*/*.js" "app/*.js"

      - run:
          name: Standard js style check on app js files
          command: |
            ~/npm-global/bin/standard --fix app/*/*.js app/*.js

  PrepareProject:
    executor: nodeandroiddocker
    steps:
      - *fast-checkout

      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
            - v2-npm-deps-

      - run:
          name: Install npm local modules
          command: |
            npm i --no-progress;

      - save_cache:
          paths:
            - node_modules
          key: v2-npm-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Update android manifest and iOS Info.plist versions
          command: |
            node ./scripts/update-version.js

      - run:
          name: Build setup
          command: |
            rm -rf platforms;

      - persist_to_workspace:
          root: ~/
          paths:
              - NativescriptAppBuild

  BuildReleaseAndroid:
    executor: nodeandroiddocker
    steps:
      - *fast-checkout

      - restore_cache:
          keys:
            - v3-npm-global

      - restore_cache:
          keys:
            - v3-android-npm-deps-{{ checksum "package-lock.json" }}
            - v3-android-npm-deps-

      - run:
          name: Adding platform
          command: |
            ~/npm-global/bin/tns platform add android;
            cp ./app/App_Resources/Android/gradle.properties ./platforms/android/gradle.properties;
            echo $ANDROID_KEY_BASE64 | base64 -d > ./key.jks;
            echo $PLAY_STORE_JWT > ./jwt.json;
            /usr/local/openjdk-8/bin/keytool -list -v -keystore ./key.jks -alias "${KEY_STORE_ALIAS}" -storepass "${KEY_STORE_ALIAS_PASSWORD}" -keypass "${KEY_STORE_ALIAS_PASSWORD}"|grep "Certificate fingerprints" -A 3
            /usr/local/openjdk-8/bin/keytool -exportcert -keystore ./key.jks -alias "${KEY_STORE_ALIAS}" -storepass "${KEY_STORE_ALIAS_PASSWORD}" -keypass "${KEY_STORE_ALIAS_PASSWORD}"|openssl sha1 -binary | openssl base64

      - save_cache:
          paths:
            - node_modules
          key: v3-android-npm-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Build signed app
          environment:
            ANDROID_KEY_BASE64: ""
            PLAY_STORE_JWT: ""
          command: |
            ~/npm-global/bin/tns build android --release --key-store-path ./key.jks --key-store-password "${KEY_STORE_PASSWORD}" --key-store-alias "${KEY_STORE_ALIAS}" --key-store-alias-password "${KEY_STORE_ALIAS_PASSWORD}" --copy-to ./dist/build.apk;

      - persist_to_workspace:
          root: ~/
          paths:
              - NativescriptAppBuild/dist

      - store_artifacts:
          path: ./dist

  DistributeAndroid:
    executor: nodeandroiddocker
    steps:
      - *fast-checkout

      - restore_cache:
          keys:
            - v3-npm-global

      - run:
          name: Publish apk to firebase app distribution
          command: |
            export GIT_COMMIT_MESSAGE="$(git log --format=%B -n 1 $CIRCLE_SHA1)"
            echo ${APP_DIST_ANDROID_GROUP}|base64;
            echo $GIT_COMMIT_MESSAGE;
            ~/npm-global/bin/firebase appdistribution:distribute ./dist/build.apk --app ${APP_DIST_ANDROID_ID} --release-notes "$GIT_COMMIT_MESSAGE" --groups ${APP_DIST_ANDROID_GROUP} --token ${FIREBASE_TOOLS_TOKEN}

  appSyncDistributeAndroid:
    executor: nodeandroiddocker
    steps:
      - *fast-checkout

      - restore_cache:
          keys:
            - v3-npm-global

      - run:
          name: Publish update to app sync
          command: |
            echo $nativescriptAppSyncKey | base64 -d > ~/.nativescript-app-sync.config;
            ./scripts/publishAppSync.sh

  Completed:
    executor: nodeandroiddocker
    steps:
      - run:
          name: Completed
          command: |
            echo "Build completed"

workflows:
  version: 2
  BuildAndDistribute:
    jobs:
      - CheckoutCode
      - setupGlobal:
            requires:
                  - CheckoutCode
      - styleCheck:
            requires:
                  - setupGlobal
      - PrepareProject:
            requires:
                  - setupGlobal
      - BuildReleaseAndroid:
            requires:
                  - PrepareProject
                  - styleCheck
      - appSyncDistributeAndroid:
            requires:
                  - BuildReleaseAndroid
      - DistributeAndroid:
            requires:
                  - BuildReleaseAndroid

      - Completed:
            requires:
                  - DistributeAndroid
                  - appSyncDistributeAndroid

#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /.*/
