name: Debug build app

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install NPM dependancies
        run: sudo npm i -g nativescript@latest firebase-tools

      - name: Setup ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install fastlane
        run: bundle install


      - name: Build debug apk for android
        run: npm run buildDebugAndroid

# @todo renable build artifact upload after upgrading github
#      - name: Upload build artifact to github
#        uses: actions/upload-artifact@v2
#        with:
#          name: app-debug.apk
#          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Distribute to firebase app testing
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}            
        run: npm run distributeDebugAndroid "CI Build-$GITHUB_REF $GITHUB_SHA"